### ISSUE TITLE
I didn't know how to message you so I came here.

### ISSUE THREAD

**Issue by munecito** [ewaldc/realtek-r8125-dkms#1]
Hello @ewaldc 

I am munecito from the https://github.com/Joshua-Riek/ubuntu-rockchip/issues/1068 thread.

Because that project will be most probably closed I wanted to give you an update on my issue.

Since the project won't be getting updates I went and installed the offcial ubuntu image from orange pi.

That one has an orangepi-config facility to transfer the OS to the NVME, and you can also modify u-boot from there. Once I installed that image I can shut down the board and restart with the USB C SSD connected. I didn't need to add anything to u-boot although I think I had identify some line in the copy of the u-boot you left (thank you for that) that could have potentially helped.

I just wanted to give you a heads up just in case you would like to check out those official ubuntu images for those boards in which you had observed a similar boot loop.

This is what shows when booting regarding the system:

Welcome to Orange Pi 1.1.8 Jammy with Linux 6.1.43-rockchip-rk3588

Kind regards.

PS: I managed to change the sources and forced an update to noble. Everything seems to be working so far and the boot supports the SSD.

 Static hostname: orangepi5
       Icon name: computer
      Machine ID: XXXXXXXXXXXXXXXX
         Boot ID: XXXXXXXXXXXXX
Operating System: Ubuntu 24.04.1 LTS
          Kernel: Linux 6.1.43-rockchip-rk3588
    Architecture: arm64
orangepi@orangepi5:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 24.04.1 LTS
Release:        24.04
Codename:       noble

**Comment by ewaldc** [comment]
Good job!  It's not Joshua's fault, this is how u-boot is generally configured: boot from USB ahead of NVME.  It's also true for most PC's, but on a PC, you can easiliy change the boot order in BIOS or with grub(2).   Will close this "issue" here,
